### ISSUE TITLE
baresip dial in LAN meet call: sipsess_connect: Function not implemented

### ISSUE THREAD

**Issue by codedigger123** [alfredh/baresip#298] opened 2017-09-13 07:32 UTC
I use baresip in LAN as following chart.The IP of SIP Server is 192.168.115.164 and the user of client1 is 1000  and user of client2 is 1001
                                            
SIP client1---------SIP Server------SIP client2

when I dial client2,I meet the flowing error

>       d sip:1001@192.168.115.164
call: connecting to 'd sip:1001@192.168.115.164'..
call: sipsess_connect: Function not implemented
menu: ua_connect failed: Function not implemented

I think dialing is the basic function.why it turn out to be not implemented?
can someone help?thanks!

**Comment by codedigger123** [comment] 2017-09-13 08:19
It is caused by the wrong parameter of the input parameter(call->peer_uri) in send_invite function in call.c.I use the following command will listen the ring audio
./baresip -e "d sip:1001@192.168.115.164"

but it will cause another call fail error:
All 1 useragent registered successfully! (2 ms)
call: SIP Progress: 100 trying -- your call is important to us (/)
call: SIP Progress: 180 Ringing (/)
call: SIP Progress: 180 Ringing (/)
call: SIP Progress: 180 Ringing (/)
sip:1001@192.168.115.164: session closed: 488 Not Acceptable here

**Comment by alfredh** [comment] 2017-09-15 17:48
Can you please include the full log and the config used?

From your log:

```
call: connecting to 'd sip:1001@192.168.115.164'..
```

if the uri dialled is prefixed with a valid scheme, it must be "sip:".
In your case it is `d ` which is wrong.

You can use the long command `/dial` or short command `d` to dial out.

The 488 error is coming from the target Client, can you please include the
ngrep trace of the SIP traffic and the log from the target Client?


/Alfred

**Comment by anug7** [comment] 2017-09-17 02:02
@alfredh , via #299, I am calling from the baresip shell. I am adding the baresip log for you information.
[error_call_log.txt](https://github.com/alfredh/baresip/files/1308784/error_call_log.txt)

**Comment by gunasekaran7** [comment] 2017-09-20 03:49
Any updates on this? I am also stuck with the same error.

**Comment by alfredh** [comment] 2017-09-20 19:21
@anug7 your log file is full of debug lines that are not coming from stock baresip, such as:

```
Change Vin sensor clock = 20000000
Trigger stop
Trigger start
```

can you please compile stock baresip@HEAD from github and reproduce
the bug. it is helpful if you reports include:

- Baresip version
- Libre version
- Name and version of Operating System
- baresip config files
- ngrep trace of SIP traffic.


/Alfred

**Comment by anug7** [comment] 2017-09-21 13:28
please find attached info

Setup info:
Caller: baresip v0.5.5 (libre version: 0.5.4) running on arm platform with Linux based custom OS.
Callee: linphone running on Ubuntu 14.04

I have attached the ngrep log on the callee side (couldn't run ngrep on caller side) and the baresip config file on the caller side.

[ngrep_calle_log.txt](https://github.com/alfredh/baresip/files/1321328/ngrep_calle_log.txt)
[caller_baresip_config.txt](https://github.com/alfredh/baresip/files/1321329/caller_baresip_config.txt)

**Comment by alfredh** [comment] 2017-09-21 16:14
Hi @anug7 

from your SIP trace I can see that one record route has a SIPS uri:

```
Record-Route: <sips:37.59.51.72:5223;lr>.
```

the 200 OK is re-transmitted because it is dropped by baresip,
while the other agent is waiting for ACK. after a while the other agent
gives up and sends BYE.

SIPS scheme is not supported by baresip/libre.

I suggest you try again with another SIP proxy or try to disable sips.


this ticket now contains 3 different issues :) it is easier to debug if one issue
only contains one problem/bug.

I will close the issue now. You are welcome to create a new issue
with a clear problem description incl. logs.


/Alfred

**Closed by alfredh** 2017-09-21 16:14 UTC

**Comment by seleznevsergey** [comment] 2017-11-16 09:11
This problem occur when you try to call to 'd sip:1001@192.168.115.164' instead 'sip:1001@192.168.115.164'. Try to run baresip -> press 'd' -> input 'sip:1001@192.168.115.164'
