### ISSUE TITLE
wincons: Segmentation fault when unloading

### ISSUE THREAD

**Issue by GGGO** [alfredh/baresip#151] opened 2016-08-14 11:01 UTC
Sometimes I got a segfault when baresip unloads wincons module.

The debug shows that it failed on `while (st->run) {` in `static DWORD WINAPI input_thread(LPVOID arg)`

baresip seems to use volatile for R/W locking in others modules, so.

```
struct ui_st {
    struct tmr tmr;
    struct mqueue *mq;
    HANDLE hThread;
-   bool run;
+   volatile bool run;
    HANDLE hstdin;
    DWORD  mode;
};
```

**Comment by GGGO** [comment] 2016-08-14 16:57
volatile didn't help... I got another segfault on `while (st->run)`

I'm cross compiling with MinGW 5.2.0-1

**Comment by alfredh** [comment] 2016-10-30 12:17
I think the problem is that the input_thread is still running after the ui_st object
is destroyed.


in other modules we have solved this by using `pthread_join` that will block execution
until the worker-thread is completely exited.


could you try to add a call to `WaitForSingleObject` in the destructor:


```
--- a/modules/wincons/wincons.c
+++ b/modules/wincons/wincons.c
@@ -43,6 +43,7 @@ static void destructor(void *arg)
                SetConsoleMode(GetStdHandle(STD_INPUT_HANDLE), st->mode);
 
        st->run = false;
+       WaitForSingleObject(st->hThread, INFINITE);
        CloseHandle(st->hThread);

```

**Comment by alfredh** [comment] 2016-11-20 16:19
@GGGO I have pushed a fix for this, please test and verify it.

**Closed** 2016-11-20 16:18 UTC
