### ISSUE TITLE
Coredump on incoming call

### ISSUE THREAD

**Issue by robdyck** [alfredh/baresip#940] opened 2020-03-17 03:54 UTC
Linux on Fedora
From git.
Coredump follows.

           PID: 614261 (baresip)
           UID: 1000 (rdyck)
           GID: 1000 (rdyck)
        Signal: 11 (SEGV)
     Timestamp: Mon 2020-03-16 20:46:49 PDT (1min 8s ago)
  Command Line: baresip -v
    Executable: /usr/local/bin/baresip
 Control Group: /user.slice/user-1000.slice/session-454.scope
          Unit: session-454.scope
         Slice: user-1000.slice
       Session: 454
     Owner UID: 1000 (rdyck)
       Boot ID: adde4db17c444cc498b54ff13618819f
    Machine ID: 880918cfecb14877a508dfde3dbbf333
      Hostname: blacky.mylan
       Storage: /var/lib/systemd/coredump/core.baresip.1000.adde4db17c444cc498b54ff13618819f.614261.1584416809000000000000.lz4
       Message: Process 614261 (baresip) of user 1000 dumped core.
                
                Stack trace of thread 614261:
                #0  0x00007f152ed96b6a __GI___strlen_sse2 (libc.so.6)
                #1  0x00007f152f42f23a str_len (libre.so)
                #2  0x00007f152f42d463 re_vhprintf (libre.so)
                #3  0x00007f152f42e168 re_vsnprintf (libre.so)
                #4  0x000000000041c99f vlog (baresip)
                #5  0x000000000041cc90 info (baresip)
                #6  0x00007f1529eef748 ua_event_handler (menu.so)
                #7  0x000000000042468d ua_event (baresip)
                #8  0x0000000000424f57 call_event_handler (baresip)
                #9  0x0000000000412d3f call_event_handler (baresip)
                #10 0x000000000041620b call_accept (baresip)
                #11 0x00000000004270ee sipsess_conn_handler (baresip)
                #12 0x00007f152f3faf55 invite_handler (libre.so)
                #13 0x00007f152f3fafc9 request_handler (libre.so)
                #14 0x00007f152f3f2116 sip_recv (libre.so)
                #15 0x00007f152f3f23e6 udp_recv_handler (libre.so)
                #16 0x00007f152f420e33 udp_read (libre.so)
                #17 0x00007f152f420e7c udp_read_handler (libre.so)
                #18 0x00007f152f430366 fd_handler (libre.so)
                #19 0x00007f152f431339 fd_poll (libre.so)
                #20 0x00007f152f431637 re_main (libre.so)
                #21 0x000000000042c0db main (baresip)
                #22 0x00007f152ed1e1a3 __libc_start_main (libc.so.6)
                #23 0x000000000040b11e _start (baresip)

**Comment by alfredh** [comment] 2020-03-19 11:26
which version of Fedora are you using ?

can you also include the corresponding log, and a more detailed backtrace that shows
the line numbers?

how was the bug triggered?

**Comment by robdyck** [comment] 2020-03-19 15:50
Fedora 31
fault triggered by answering an incoming call.
[baresip.txt](https://github.com/alfredh/baresip/files/4355522/baresip.txt)

**Comment by alfredh** [comment] 2020-03-20 17:47
thanks

can you also share your config and account to see how the system is configured ?

your log contains a lot of unrelated warnings:

```
dl: mod: /usr/local/lib/baresip/modules/opus.so (/usr/local/lib/baresip/modules/opus.so: cannot open shared object file: No such file or directory)
dl: mod: /usr/local/lib/baresip/modules/g722.so (/usr/local/lib/baresip/modules/g722.so: cannot open shared object file: No such file or directory) 
dl: mod: /usr/local/lib/baresip/modules/swscale.so (/usr/local/lib/baresip/modules/swscale.so: cannot open shared object file: No such file or directory)                                                                                                                                               
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM A-4d0db0


```

please either make sure that the modules are built, or comment them out
in the config.

there is also this in your log:

```
call: rejecting incoming call from sip:4@192.168.1.2 (500 Server Error)
```

do you know where this is coming from ?

please run baresip again with the -v (verbose) flag.

the reason for the crash is here:

```
#1  0x00007ffff7f6123a in str_len (s=0xb5b5b5b5b5b5b5b5 <error: Cannot access memory at address 0xb5b5b5b5b5b5b5b5>) at src/fmt/str.c:141
```

0xb5b5b5b5... means that the object has already been destroyed.

**Comment by robdyck** [comment] 2020-03-20 19:28
Sorry about the noise. I wasn't to concerned about the missing modules.
"500 Server Error" is internal from the call_hangup function.
"ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM A-4d0db0"
I sort of looked at that as a project for myself to learn about debugging C. I think I can give you a little insight about that. I tried printing the device name at various points. The device name changes from "default" to "A-xxxxxx" at some point. xxxxxx changes with each run but looks similar to pointers used for instance the pointer to struct audio.
[baresp-config.txt](https://github.com/alfredh/baresip/files/4361493/baresp-config.txt)

**Comment by robdyck** [comment] 2020-03-20 20:01
The verbose option does'nt seem to add much. I am attaching backtrace again. As you can see there seems to be problem with some of my debug libs.
[baresip-verbose-coredump.txt](https://github.com/alfredh/baresip/files/4361608/baresip-verbose-coredump.txt)

**Comment by alfredh** [comment] 2020-03-21 12:50
Hi,

I think I have found the problem with the crash.

from your config:

```
module_app		echo.so
module_app		menu.so
```

both modules should not be loaded at the same time.

echo.so will automatically answer incoming calls.
menu.so is the interactive SIP client with a UI

which one do you intend to use ?

the core of the problem is here:

```c
void ua_event(struct ua *ua, enum ua_event ev, struct call *call,
	      const char *fmt, ...)
{
	struct le *le;
	char buf[256];
	va_list ap;

	va_start(ap, fmt);
	(void)re_vsnprintf(buf, sizeof(buf), fmt, ap);
	va_end(ap);

	/* send event to all clients */
	le = uag.ehl.head;
	while (le) {
		struct ua_eh *eh = le->data;
		le = le->next;

		eh->h(ua, ev, call, buf, eh->arg);
	}
}
```

and in echo.so:

```c
static void ua_event_handler(struct ua *ua, enum ua_event ev,
		struct call *call, const char *prm, void *arg)
{
	int err;
	(void)prm;
	(void)arg;

	switch (ev) {

	case UA_EVENT_CALL_INCOMING:
		debug("echo: CALL_INCOMING: peer=%s  -->  local=%s\n",
				call_peeruri(call),
				call_localuri(call));

		err = new_session(ua, call);
		if (err) {
			ua_hangup(ua, call, 500, "Server Error");
		}
		break;

	default:
		break;
	}
}
```

the function `new_session` fails, and then it calls `ua_hangup` which
will deref `call`. the next iteration of ua_event, the call object is corrupt.

your config contains a lot of stuff from old versions; I would strongly
suggest that you make a complete clean build and config, and try again.

also try `make test` to verify that all libraries are good.

**Comment by robdyck** [comment] 2020-03-21 15:41
Indeed I was using a config file from months ago. I recently decided to revisit baresip and compiled the latest version from git. I don't remember what I had intended with echo. I ran into trouble trying to use a non-default alsa setup. I have now eliminated config and let baresip create a new file. I can confirm that the default config but with my preferred audio device, eliminates both the problems I was seeing (bogus audio device and segflt). Perhaps some boilerpate in the code would prevent a potential problem. I will try "make test". By the way, do you plan to add video to the android version?
Thank you for your response.

**Comment by alfredh** [comment] 2020-03-21 21:41
thanks for the report, I will close the issue

for Android I am not sure, at least this has to be done:

- enable a video source (e.g. avformat with android-camera device)
- enable a video codec (e.g. avcodec.so)
- enable a video display (e.g. opensles.so or something else).

**Closed by alfredh** 2020-03-21 21:41 UTC

**Comment by juha-h** [comment] 2020-03-29 14:36
Alfred E. Heggestad writes:

> for Android I am not sure, at least this has to be done:
> 
> - enable a video source (e.g. avformat with android-camera device)

I have tried to do this by building ffmpeg libs with android_camera
input device enabled:

Enabled indevs:
android_camera fbdev lavfi v4l2

Then in config file, I wrote

video_source avformat,android_camera

and also

video_source avformat,"Android camera input device"

but both resulted in no such file error:

03-29 17:32:12.852 18505 18556 D Baresip Lib: avformat: video: alloc dev='android_camera'
03-29 17:32:12.853 18505 18556 D Baresip Lib: avformat: avformat_open_input(android_camera) failed (ret=No such file or directory)

Does anyone have a suggestion on how android_camera file name should be
written or what else may cause the error?

The app has camera permission enabled.

-- Juha

**Comment by alfredh** [comment] 2020-03-29 15:44
I think you have to modify the code in avformat module:

```c
	ret = avformat_open_input(&st->ic, dev, NULL, NULL);
	if (ret < 0) {
		warning("avformat: avformat_open_input(%s) failed (ret=%s)\n",
			dev, av_err2str(ret));
		err = ENOENT;
		goto out;
	}
```

the prototype is:

```c
int avformat_open_input(AVFormatContext **ps, const char *url, ff_const59 AVInputFormat *fmt, AVDictionary **options);
```

use this function to find the correct AVInputFormat:

```c
ff_const59 AVInputFormat *av_find_input_format(const char *short_name);
```

the short_name is probably "android_camera"

**Comment by juha-h** [comment] 2020-03-29 16:25
Alfred E. Heggestad writes:

> I think you have to modify the code in avformat module:

Thanks for the hint.  I tried like this:

```
	ff_const59 AVInputFormat *input_format;

    input_format = av_find_input_format(dev);

	if (!input_format) {
		warning("avformat: av_find_input_format(%s) not found\n",
			dev);
		err = ENOENT;
		goto out;
	}
	       
	ret = avformat_open_input(&st->ic, dev, input_format, NULL);
```
but unfortunately input format was not found:
```
03-29 19:21:19.688 21409 21448 D Baresip Lib: avformat: video: alloc dev='android_camera'
03-29 19:21:19.689 21409 21448 D Baresip Lib: avformat: av_find_input_format(android_camera) not found
```

**Comment by juha-h** [comment] 2020-03-31 12:07
I tested and found out that its cameras have CameraMetadata.INFO_SUPPORTED_HARDWARE_LEVEL_LEGACY, which is not supported by Android Camera2 NDK API.

Perhaps it would anyway make sense to include the input_format code to avformat.c.

**Comment by juha-h** [comment] 2020-04-07 13:35
I bought a new Android device that supports Camera2 API and made some progress! avdevice_register_all() needs to be called before av_find_input_format().  Otherwise nothing is found.  After I add that, video call gave these log messages:
```
04-07 16:22:23.772 26302 26348 D Baresip Lib: Set video encoder: H265  (500000 bit/s, 25.00 fps)
04-07 16:22:23.772 26302 26348 D Baresip Lib: avcodec: h265 encoder activated
04-07 16:22:23.772 26302 26348 D Baresip Lib: avcodec: video encoder H265: 25.00 fps, 500000 bit/s, pktsize=1024
04-07 16:22:23.772 26302 26348 D Baresip Lib: video: no video display
04-07 16:22:23.772 26302 26348 D Baresip Lib: avformat: video: alloc dev='android_camera'
04-07 16:22:24.197 26302 26348 D Baresip Lib: [android_camera @ 0x7a7edf0800] Requested video_size 0x0 not available, falling back to 4208x3120
04-07 16:22:24.221 26302 26348 D Baresip Lib: [android_camera @ 0x7a7edf0800] Android camera capture session is active.
04-07 16:22:24.589 26302 26348 D Baresip Lib: avformat: 'video' using decoder 'rawvideo' (raw video)
04-07 16:22:24.589 26302 26348 D Baresip Lib: call: stream start (active=1)
04-07 16:22:24.589 26302 26348 D Baresip Lib: opus: encoder fmtp (stereo=1;sprop-stereo=1;maxaveragebitrate=28000;cbr=0;useinbandfec=1)
04-07 16:22:24.589 26302 26348 D Baresip Lib: audio: start
04-07 16:22:24.591 26302 26348 D Baresip Lib: Set video decoder: H265 
04-07 16:22:24.591 26302 26348 D Baresip Lib: avcodec: h265 decoder activated
04-07 16:22:24.591 26302 26348 D Baresip Lib: avcodec: decode: hardware accel disabled
04-07 16:22:24.591 26302 26348 D Baresip Lib: avcodec: video decoder H265 ()
04-07 16:22:24.591 26302 26347 D Baresip Lib: ua event (CALL_ESTABLISHED) sip:test@test.tutpro.com
04-07 16:22:25.014 26302 26348 D Baresip Lib: [android_camera @ 0x7a7edf0800] 
04-07 16:22:25.014 26302 26348 D Baresip Lib: Input queue was full, dropping frame, consider raising the input_queue_size option (current value: 5)
04-07 16:22:25.054 26302 26348 D Baresip Lib: [android_camera @ 0x7a7edf0800] 
04-07 16:22:25.054 26302 26348 D Baresip Lib: Input queue was full, dropping frame, consider raising the input_queue_size option (current value: 5)
...
```

**Comment by alfredh** [comment] 2020-04-07 13:43
can you please create a new PR/Issue for this ?

the H.265 video codec is very CPU intensive, it is probably better
to use H.263 or H.264 instead.

**Comment by juha-h** [comment] 2020-04-07 13:57
Alfred E. Heggestad writes:

> can you please create a new PR/Issue for this ?

Just did that before reading your comment.

> the H.265 video codec is very CPU intensive, it is probably better
> to use H.263 or H.264 instead.

OK, I'll try with those too if they help in getting rid of the "input
queue was full" messages.

Any recommendation on video_size?  I haven't yet figured out how to
configure that.

Also, I haven't yet figured out how to choose the front camera that has
id 1.

I guess I don't need to worry about this, since there is no video
display yet:
```
avformat: 'video' using decoder 'rawvideo' (raw video)
```
